language: node_js
node_js: node
scripts:
  - npm install
jobs:
  include:
    - stage: Produce Coverage
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: build
      name: Build Lib
      script:
        - npm run lint
        - npm run test
        - npm run build
    - stage: deploy
      name: Deploy Lib
      before_deploy:
        - npm run build
      deploy:
        provider: npm
        email: stesel23@gmail.com
        api_key: $NPM_AUTH_TOKEN
        skip_cleanup: true
        on:
          branch: master
