language: node_js
node_js: 11
scripts:
  - yarn
jobs:
  include:
    - stage: Produce Coverage
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: build
      name: Build Lib
      script:
        - yarn lint
        - yarn test
        - yarn build
    - stage: deploy
      name: Deploy Lib
      before_deploy:
        - yarn build
      deploy:
        provider: npm
        email: stesel23@gmail.com
        api_key: $NPM_AUTH_TOKEN
        skip_cleanup: true
        on:
          branch: master
