name: Coverage
on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Coverage
      run: npm run coverage
    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
        with:
          branches: master
